name: Build java

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        name: setup graalvm
        with:
          java-version: '17' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: install native-image
        run: gu install native-image
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: make build-java-github
      - uses: actions/cache@v3
        with:
          path: build/libs/devtoolbelt.jar
          key: ${{ runner.os }}-jar-${{ github.sha }}
