name: deploy-staging

on:
  workflow_run:
    workflows: ['Create and publish a Docker image']
    types:
      - completed

jobs:
  build:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dev-toolbelt-staging"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - run: |
          docker pull ghcr.io/brunoshiroma/dev-toolbelt:develop
          heroku container:login
          docker tag ghcr.io/brunoshiroma/dev-toolbelt:develop registry.heroku.com/dev-toolbelt-staging/web
          docker push registry.heroku.com/dev-toolbelt-staging/web
          heroku container:release web --app dev-toolbelt-staging
