name: deploy-production

on:
  workflow_run:
    workflows: ['docker build']
    types:
      - completed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dev-toolbelt"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - run: |
          docker pull ghcr.io/brunoshiroma/dev-toolbelt:main
          heroku container:login
          docker tag ghcr.io/brunoshiroma/dev-toolbelt:main registry.heroku.com/dev-toolbelt/web
          docker push registry.heroku.com/dev-toolbelt/web
          heroku container:release web --app dev-toolbelt
